apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pi-k3s.io/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: operations
  labels:
    pi-k3s.io/managed: "true"
